# Generated by Django 3.2.11 on 2022-01-28 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='my_company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comp', models.CharField(default='', max_length=1000)),
                ('created_by', models.CharField(default='', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='my_ledger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ledger_list', models.CharField(default='', max_length=1000)),
                ('created_by', models.CharField(default='', max_length=1000)),
                ('company_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ledger.my_company')),
            ],
        ),
    ]
