# Generated by Django 3.2.11 on 2022-01-28 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='my_ledger',
            old_name='created_by',
            new_name='lcreated_by',
        ),
    ]
