# Generated by Django 3.2.11 on 2022-01-31 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0002_rename_created_by_my_ledger_lcreated_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='lUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30)),
                ('email', models.EmailField(default='', max_length=254)),
                ('number', models.PositiveIntegerField()),
                ('password', models.CharField(default='', max_length=15)),
            ],
        ),
    ]
