# Generated by Django 4.0.1 on 2022-01-18 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=15)),
                ('emai', models.EmailField(default='', max_length=15)),
                ('age', models.IntegerField()),
                ('DOB', models.DateField()),
            ],
        ),
    ]
