# Generated by Django 3.2.9 on 2022-01-03 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testserial',
            name='field2',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AddField(
            model_name='testserial',
            name='field3',
            field=models.CharField(default='', max_length=12),
        ),
    ]
