# Generated by Django 4.0.1 on 2022-01-10 04:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0004_invoicetodb_alter_showdata_email_alter_showdata_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cn', models.CharField(max_length=50, verbose_name='Company_Name')),
            ],
        ),
        migrations.CreateModel(
            name='Plo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Buyer_data', models.CharField(max_length=50)),
                ('In', models.CharField(max_length=50, unique=True, verbose_name='Invoice Number')),
                ('In_date', models.CharField(max_length=50, verbose_name='Invoice Date')),
                ('C', models.CharField(max_length=50, verbose_name='State Code')),
                ('T', models.CharField(max_length=50, verbose_name='Total')),
                ('G', models.CharField(max_length=50, verbose_name='GST Toal')),
                ('file', models.FileField(default='', null=True, upload_to='in/')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='test1.comp')),
            ],
        ),
    ]
