# Generated by Django 3.2.11 on 2022-01-24 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('files', models.FileField(blank=True, null=True, upload_to='Document/')),
                ('recieved_from2', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UserDetails2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30)),
                ('email', models.EmailField(default='', max_length=254)),
                ('number', models.PositiveIntegerField()),
                ('password', models.CharField(default='', max_length=15)),
                ('userfiles', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='share2.filelist')),
            ],
        ),
    ]
