# Generated by Django 3.2.11 on 2022-01-24 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share2', '0002_auto_20220124_0646'),
    ]

    operations = [
        migrations.AddField(
            model_name='filelist',
            name='uploaded_by',
            field=models.CharField(default='', max_length=50),
        ),
    ]
