# Generated by Django 3.2.11 on 2022-01-27 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share2', '0003_filelist_uploaded_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
