# Generated by Django 3.2.11 on 2022-01-27 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share2', '0004_ip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ip',
            name='address',
        ),
        migrations.AddField(
            model_name='ip',
            name='global_ipaddress',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='ip',
            name='local_ipaddress',
            field=models.CharField(default='', max_length=150),
        ),
    ]
