# Generated by Django 4.0.1 on 2022-01-19 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CA', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='number',
            field=models.PositiveIntegerField(default='', max_length=10),
        ),
    ]
