# Generated by Django 4.0.1 on 2022-01-19 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CA', '0002_alter_signup_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='number',
            field=models.PositiveIntegerField(),
        ),
    ]
