# Generated by Django 4.0.1 on 2022-01-20 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CA', '0005_rename_signup_casignup_prsignup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prsignup',
            name='recommend_by',
            field=models.CharField(default='', max_length=30),
        ),
    ]
