# Generated by Django 4.0.1 on 2022-01-20 08:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CA', '0006_alter_prsignup_recommend_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='casignup',
            name='payment_due_date',
            field=models.DateField(default=datetime.datetime(2022, 2, 4, 8, 46, 18, 518359)),
        ),
        migrations.AddField(
            model_name='prsignup',
            name='payment_due_date',
            field=models.DateField(default=datetime.datetime(2022, 2, 4, 8, 46, 18, 518677)),
        ),
    ]
