# Generated by Django 4.0.1 on 2022-01-21 10:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CA', '0007_casignup_payment_due_date_prsignup_payment_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casignup',
            name='payment_due_date',
            field=models.DateField(default=datetime.datetime(2022, 2, 5, 10, 2, 25, 929620)),
        ),
        migrations.AlterField(
            model_name='prsignup',
            name='payment_due_date',
            field=models.DateField(default=datetime.datetime(2022, 2, 5, 10, 2, 25, 929886)),
        ),
    ]
