# Generated by Django 3.2.11 on 2022-01-22 07:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CA', '0008_alter_casignup_payment_due_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casignup',
            name='payment_due_date',
            field=models.DateField(default=datetime.datetime(2022, 2, 6, 7, 20, 53, 533654)),
        ),
        migrations.AlterField(
            model_name='prsignup',
            name='payment_due_date',
            field=models.DateField(default=datetime.datetime(2022, 2, 6, 7, 20, 53, 534270)),
        ),
    ]
