# Generated by Django 3.2.11 on 2022-01-24 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0002_auto_20220122_0719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
    ]
